config/routes.rb
NestedModel::Application.routes.draw do
  resources :projects

  root :to => 'projects#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :persons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end

  def create
  end

  def new
    @projects =Project.new
    @projects.persons.build
   end

  def update
  end

  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedModel</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<%= link_to "add", new_project_path %>

app/views/projects/new.html.erb
<%= semantic_form_for [@projects,@persons] do |f| %>
    <%= f.inputs %>
    
    <h2>person</h2>
    
    <%= form.semantic_fields_for :person do |person| %>
    <%= person.inputs %>
  <% end %>

    <%= f.buttons %>
  <% end %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>